source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/nenhall/NHNavigationItem.git'
platform :ios, '8.0'

target 'NHExtensionDemo' do
    # use_frameworks!
    pod 'NHExtension', :path => '../NHExtension.podspec'
    # pod 'NHHUDExtend'
    #pod 'NHNavigationItem'
    pod 'Masonry'
end
