# Uncomment the next line to define a global platform for your project
# platform :ios, '6.0'

target 'NHExtensionDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'NHHUDExtend', :path => ‘../NHExtension.podspec'


end
